{{- if .Values.main.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.main.service.nameOverride }}
  name: {{ .Values.main.service.nameOverride | quote }}
  {{- else }}
  name: {{ include "ns-go.fullname" . | quote }}
  {{- end }}
  labels:
    {{- include "ns-go.labels" . | nindent 4 }}
  annotations:
    {{- include "ns-go.main.annotations" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ns-go.main.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.main.service.ports }}
    - name: {{ .name }}
      port: {{ .ports.external }}
      targetPort: {{ .ports.internal }}
      protocol: {{ .protocol }}
    {{- end }}
{{- end }}
