{{- if .Values.logging.enabled }}
{{- range $name, $v := .Values.instances }}
{{- if $v.enabled }}

{{- $appConfig := dict }}
{{- if $v.appConfig }}
{{- $appConfig = mergeOverwrite (deepCopy $.Values.common.appConfig) (deepCopy $v.appConfig) }}
{{- else }}
{{- $appConfig = $.Values.common.appConfig }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "ns-go.fullname" $ }}-{{ $name }}-logging"
  labels:
    {{- include "ns-go.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  annotations:
    {{- include "ns-go.common.annotations" $ | nindent 4 }}
data:
  {{- if $.Values.logging.vector.enabled }}
  vector.toml: |-
    {{- include "lib_logging.common.vector.config" (list $ . $appConfig) | nindent 4 }}
  {{- end }}
...
{{- end }}
{{- end }}
{{- end }}
