{{- range $name, $v := .Values.instances }}
{{- if $v.enabled }}

{{- $appConfig := dict }}
{{- if $v.appConfig }}
{{- $appConfig = mergeOverwrite (deepCopy $.Values.common.appConfig) (deepCopy $v.appConfig) }}
{{- else }}
{{- $appConfig = $.Values.common.appConfig }}
{{- end }}

{{- $config := mergeOverwrite (deepCopy $.Values.common) (deepCopy $v) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "ns-go.fullname" $ }}-{{ $name }}"
  labels:
    {{- include "ns-go.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  annotations:
    {{- include "ns-go.common.annotations" $ | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_CLIENT_ID: {{ $appConfig.keycloak.clientId | quote }}
  KEYCLOAK_CLIENT_SECRET_KEY: {{ $appConfig.keycloak.clientSecretKey | quote }}
  POSTGRES_USERNAME: {{ $appConfig.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ $appConfig.postgres.password | quote }}
  REDIS_USERNAME: {{ $appConfig.redis.username | quote }}
  REDIS_PASSWORD: {{ $appConfig.redis.password | quote }}
  {{- with $.Values.globalExtraEnvVarsSecret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with $config.extraEnvVarsSecret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
...
{{- end }}
{{- end }}
