{{- range $name, $v := .Values.instances }}
{{- if $v.enabled }}

{{- $appConfig := dict }}
{{- if $v.appConfig }}
{{- $appConfig = mergeOverwrite (deepCopy $.Values.common.appConfig) (deepCopy $v.appConfig) }}
{{- else }}
{{- $appConfig = $.Values.common.appConfig }}
{{- end }}

{{- $config := mergeOverwrite (deepCopy $.Values.common) (deepCopy $v) }}

{{- range $appConfig.extraFiles }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "ns-go.fullname" $ }}-{{ $name }}-extra-files-{{ .path | replace "/" "-" | replace "." "-" | trimAll "-" }}"
  labels:
    {{- include "ns-go.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  annotations:
    {{- include "ns-go.common.annotations" $ | nindent 4 }}
stringData:
  {{- range .files }}
  {{ .name }}: |
{{ tpl .content $ | indent 4 }}
  {{- end }}
...
{{- end }}
{{- end }}
{{- end }}
