---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ns-go.fullname" . | quote }}
  labels:
    {{- include "ns-go.main.labels" . | nindent 4 }}
  annotations:
    {{- include "ns-go.main.annotations" . | nindent 4 }}
data:
  KEYCLOAK_SERVER_URL: {{ .Values.appConfig.keycloak.url | quote }}
  KEYCLOAK_REALM_NAME: {{ .Values.appConfig.keycloak.realm | quote }}
  LOG_DIR: {{ .Values.appConfig.log.dir | quote }}
  LOG_FILENAME: {{ .Values.appConfig.log.fileName | quote }}
  LOG_LEVEL: {{ .Values.appConfig.log.level | quote }}
  LOG_FORMAT: {{ .Values.appConfig.log.format | quote }}
  LOG_FILES_COUNT: {{ .Values.appConfig.log.filesCount | quote }}
  LOG_FILE_SIZE: {{ .Values.appConfig.log.fileSize | quote }}
  STAGE: {{ .Values.appConfig.stage | quote }}
  POSTGRES_HOSTNAME: {{ .Values.appConfig.postgres.hostname | quote }}
  POSTGRES_PORT: {{ .Values.appConfig.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.appConfig.postgres.database | quote }}
  REDIS_HOSTNAME: {{ .Values.appConfig.redis.hostname | quote }}
  REDIS_PORT: {{ .Values.appConfig.redis.port | quote }}
  REDIS_DB: {{ .Values.appConfig.redis.dbNumber | quote }}
  {{- with .Values.globalExtraEnvVarsCM }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.main.extraEnvVarsCM }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
...