{{- if .Values.logging.enabled }}
{{- range $name, $v := .Values.instances }}
{{- if $v.enabled }}

{{- $appConfig := dict }}
{{- if $v.appConfig }}
{{- $appConfig = mergeOverwrite (deepCopy $.Values.common.appConfig) (deepCopy $v.appConfig) }}
{{- else }}
{{- $appConfig = $.Values.common.appConfig }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "ns-go.fullname" $ }}-{{ $name }}-logging"
  labels:
    {{- include "ns-go.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  annotations:
    {{- include "ns-go.common.annotations" $ | nindent 4 }}
data:
  {{- if $.Values.logging.vector.enabled }}
  vector.toml: |-
  {{- if $.Values.logging.vector.overrideConfig }}
{{ tpl $.Values.logging.vector.overrideConfig $ | indent 4 }}
  {{- else }}
  [sources.syslog]
  type = "syslog"
  address = "0.0.0.0:80"
  mode = "udp"

  [sinks.my_sink_id]
  type = "file"
  inputs = [ "syslog" ]
  path = "/var/lib/vector/%Y-%m-%d.log.json.zstd"
  compression = "zstd"
  encoding.codec = "json"
  {{- end }}
  {{- end }}
...
{{- end }}
{{- end }}
{{- end }}
