{{- range .Values.appConfig.extraFiles }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "ns-go.fullname" $ }}-extra-files-{{ .path | replace "/" "-" | replace "." "-" | trimAll "-" }}"
  labels:
    {{- include "ns-go.main.labels" $ | nindent 4 }}
  annotations:
    {{- include "ns-go.main.annotations" $ | nindent 4 }}
stringData:
  {{- range .files }}
  {{ .name }}: |
{{ tpl .content $ | indent 4 }}
  {{- end }}
...
{{- end }}
