{{- if .Values.migrations.enabled }}
{{- $config := mergeOverwrite (deepCopy .Values.common) (deepCopy .Values.migrations) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ns-go.fullname" . }}-migrations
  labels:
    {{- include "ns-go.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    {{- include "ns-go.migrations.annotations" . | nindent 4 }}
spec:
  backoffLimit: {{ $config.backoffLimit }}
  activeDeadlineSeconds: {{ $config.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "ns-go.labels" . | nindent 8 }}
        app.kubernetes.io/component: migrations
    spec:
      {{- if .Values.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
      {{- end }}
      securityContext:
        {{- $config.podSecurityContext | toYaml | nindent 8 }}
      restartPolicy: {{ $config.restartPolicy }}
      containers:
        - name: "{{ $config.appConfig.appName }}"
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- if $config.appConfig.appCommand }}
          command:
            {{- $config.appConfig.appCommand | toYaml | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.pullPolicy | quote }}
          resources:
            {{- $config.resources | toYaml | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ include "ns-go.fullname" . }}-migrations"
            - secretRef:
                name: "{{ include "ns-go.fullname" . }}-migrations"
          volumeMounts:
            - name: logs
              mountPath: {{ $config.appConfig.log.dir | quote }}
      volumes:
        - name: logs
          emptyDir: {}
...
{{- end }}
