apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ns-go.fullname" . | quote }}
  labels:
    {{- include "ns-go.main.labels" . | nindent 4 }}
  annotations:
    {{- include "ns-go.main.annotations" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USERNAME: {{ .Values.appConfig.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.appConfig.postgres.password | quote }}
  REDIS_USERNAME: {{ .Values.appConfig.redis.username | quote }}
  REDIS_PASSWORD: {{ .Values.appConfig.redis.password | quote }}
  {{- with .Values.globalExtraEnvVarsSecret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.main.extraEnvVarsSecret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}