ingress:

  public:
    keycloak: 'dev-keycloak.example.local'
    kong: 'dev-kong.example.local'

  hosts:
    someService: 'some-service.example.local'

stage: "dev-cloud"

postgres:
  host: 'dev-pg-cluster.example.local'
  port: 5432

redis:
  host: 'dev-redis-cluster.example.local'
  port: 6379

logging:
  enabled: true
  vector:
    enabled: true
    image:
      registry: timberio
      name: vector
      tag: 0.31.0-alpine
    dataDir: /var/lib/vector
    aggregator:
      address: vector.example.com
      port: 5044
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 50Mi
    probes:
      enabled: false
      readiness: {}
      liveness: {}
      startup: {}
    version: "1"
    tag: null
    application: "dev-cloud"
    overrideConfig: |
      [sources.syslog]
      type = "syslog"
      address = "0.0.0.0:80"
      mode = "udp"

      [sinks.my_sink_id]
      type = "file"
      inputs = [ "syslog" ]
      path = "/var/lib/vector/%Y-%m-%d.log.json.zstd"
      compression = "zstd"
      encoding.codec = "json"